org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C:/Users/Argent/.jdks/temurin-17.0.20

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.2
loom_version=1.6-SNAPSHOT

# Mod Properties
mod_version=0.5-1.20.1
maven_group=net.hasha.kafkamod

# Dependencies
fabric_api_version=0.92.11+1.20.1
